mybatis:
  mapper-locations: classpath:mapper/pixivel/*.xml, classpath:mapper/user/*.xml, classpath:mapper/system/*.xml, classpath:mapper/monitor/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    lazy-load-trigger-methods: ""
    cache-enabled: true

pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true
  reasonable: false